### ISSUE TITLE
Time extension

### ISSUE THREAD

**Issue by hayyaun** [Sharif-OS-Lab/session-1-2#21]
سلام آیا امکانش هست تایم پروژه اول تا فردا اکستند بشه ممنونم @HesamAlavian

**Comment by fatimabadiei** [comment]
> سلام آیا امکانش هست تایم پروژه اول تا فردا اکستند بشه ممنونم @HesamAlavian
بله اگه امکانش هست ممنون میشیم تایم اکستند بشه 🙏🏻

**Comment by HesamAlavian** [comment]
سلام پروژه اول اگر منظور آزمایش جلسه ۱ هست نخیر امکانش نیست. 
در مورد آزمایش جلسه ۲ ددلاین تغییر نمی‌کند ولی تا شنبه ۲۸  اسفند میتوانید ارسال کنید ( با اعمال جریمه)

**Comment by hayyaun** [comment]
من امروز تولدم بود وقتم رفت وگرنه میرسیدم. آزمایش دوم منظورم هست نصفش رو رسیدم. امکانش نیست تا صبح جریمه در نظر گرفته نشه

**Comment by fatimabadiei** [comment]
من هم gnuم arc64 هست، خیلی به مشکل خوردم، اگر جریمه رو احتساب نکنید ممنون میشم

**Comment by HesamAlavian** [comment]
@hayyaun 
شما از هفته گذشته وقت داشتید که انجام بدهید و آزمایش هم آزمایش وقت گیری نبوده است. در کلاس هم گفتم ددلاین آزمایش های ابتدایی تمدید نمی‌شود. الان هم شما می‌توانید ارسال کنید و مثل سایر دانشجوها جریمه تاخیر را داشته باشید. اگر موارد فورس ماژور شخصی یا عمومی هست به من ایمیل بزنید یا درگروه تلگرامی مخصوص گروه پردیس کیش اعلام کنید
