### ISSUE TITLE
Session 1 Report

### ISSUE THREAD

**Issue by MortezaNosratpour** [Sharif-OS-Lab/session-1-2#43]
Team Name: `[96105791-99109347-400011198]`

Student Name of member 1: `Alireza Rahmani`
Student No. of member 1: `96105791`

Student Name of member 2: `Shima Amirbeigy`
Student No. of member 2: `99109347`

Student Name of member 3: `Morteza Nosratpour`
Student No. of member 3: `400011198`

- [ ] Read Session Contents.

### Section 1.3.1
- [ ] Choose one of Virtual Machine Softwares, such as VirtualBox, VMware, ...
    1. [ ] `VirtualBox`
- [ ] Install Debian on Virtual Machine, add three screenshots from install process
    1. [ 
![2](https://github.com/Sharif-OS-Lab/session-1-2/assets/45389014/1f226298-4ec2-4535-8938-6b4cc34b3a99)] `[]`
    1. [ 
![3](https://github.com/Sharif-OS-Lab/session-1-2/assets/45389014/0fca380b-1c52-4c83-b314-68dace96b5a2)
] `[FILL HERE with image 2]`
    1. [ 
![5](https://github.com/Sharif-OS-Lab/session-1-2/assets/45389014/9b2674c9-8b60-494f-b2ea-b0a8b91c183d)
] `[FILL HERE with image 3]`

### Section 1.3.2

- [ ] Do 13 subtasks from 1 to 13 and add screenshots of each:
    1. [
![image](https://github.com/Sharif-OS-Lab/session-1-2/assets/45389014/15bfcfc5-ea0f-4691-ada4-dafb0289a1c1)
 ] `[FILL HERE with screen capture of subtask 1]`
    1. [
![image](https://github.com/Sharif-OS-Lab/session-1-2/assets/45389014/3ff1fb32-7e19-4678-a3cd-81c8cac9dc7a)
 ] `[FILL HERE with screen capture of subtask 2]`
    1. [ 
![image](https://github.com/Sharif-OS-Lab/session-1-2/assets/45389014/328d5f65-2449-43f4-8be9-2675f29d8032)
![image](https://github.com/Sharif-OS-Lab/session-1-2/assets/45389014/56a66c5e-c70c-4ac1-b544-a6ee9775cc55)
] `[FILL HERE with screen capture of subtask 3]`
    1. [ 
![image](https://github.com/Sharif-OS-Lab/session-1-2/assets/45389014/8ec09da6-0211-4630-890f-c7bc4b8aac54)
] `[FILL HERE with screen capture of subtask 4]`
    1. [ 
![image](https://github.com/Sharif-OS-Lab/session-1-2/assets/45389014/87ce914e-71f8-4f23-b41e-93e9f67433fc)
] `[FILL HERE with screen capture of subtask 5]`
    1. [ 
![image](https://github.com/Sharif-OS-Lab/session-1-2/assets/45389014/103f1820-916b-430f-8625-5b2a02a2d3c7)
] `[FILL HERE with screen capture of subtask 6]`
    1. [
![image](https://github.com/Sharif-OS-Lab/session-1-2/assets/45389014/af8c63eb-5432-4f07-9bd4-00698623e404)
 ] ``
    1. [ 
![image](https://github.com/Sharif-OS-Lab/session-1-2/assets/45389014/b63392b4-555c-443b-903f-2c83fb0b900d)
] `[FILL HERE with screen capture of subtask 8]`
    1. [ 
![image](https://github.com/Sharif-OS-Lab/session-1-2/assets/45389014/7f1424f5-4811-416b-ab4a-a0b1f03cf6d9)
] `[FILL HERE with screen capture of subtask 9]`
    1. [ 
![image](https://github.com/Sharif-OS-Lab/session-1-2/assets/45389014/73e67458-1156-4c89-b45a-41c2a91ba52a)
] `[FILL HERE with screen capture of subtask 10]`
    1. [ 
![image](https://github.com/Sharif-OS-Lab/session-1-2/assets/45389014/179f00d0-d59f-4ab4-9d3b-f0c6ba313293)
] `[FILL HERE with screen capture of subtask 11]`
    1. [ 
![image](https://github.com/Sharif-OS-Lab/session-1-2/assets/45389014/409d49b8-a345-445a-b01c-913a3104d3ab)
] `[FILL HERE with screen capture of subtask 12]`
    1. [ 
![image](https://github.com/Sharif-OS-Lab/session-1-2/assets/45389014/ef398652-be85-4a40-867c-9aff37edf53b)
] `[FILL HERE with screen capture of subtask 13]`

- For subtask 7 write difference between `>` and `>>`
    - [ [با اجرای این دو خط کد و مشاهده خروجی‎ها در تصویر ضمیمه شده متوجه می‎شویم که با قرار دادن تنها یک "<” محتوای فایل متنی پاک شده و رشته قبل علامت "<” جایگزین آن شده است ولی در حالتی که از دو "<<” استفاده شود؛ صرفا رشته قبل علامت "<<” به انتهای فایل اضافه می‎شود. تصویر مربوط به احرای این دو خط کد در قسمت بالاتر بخش vii ضمیمه شده است]

## Section 1.4 

- [ ] Write (in English or Persian) about each command:
    1. `[برای برش بخشی از هر خط در یک فایل بکار میرود و خروجی را چاپ می‎کند. این برش میتواند بر مبنای شماره بایت یا کاراکتر یا …. باشد. ]`
    1. `[این دستور نیز برای فیلتر کردن object ای در file system بکار می‎رود. معمولا برای یافتن فایلها یا دایرکتوریها و … استفاده می‎شود. فرمت آن به صورت  find [where to start searching from] [-options] [what to find] است.]`
    1. `[برای چاپ کردن n داده نخست ورودی داده شده به کار میرود. n نیز از ورودی‎های دستور است ولی مقدار پیش فرض ۱۰ نیز دارد]`
    1. `[مشابه دستور head است با این تفاوت که از داده های انتهایی فایل داده شده شروع به چاپ کردن می‎کند. ]`
    1. `[Fبرای ایجاد فایلی بدون محتوا بکار می‎رود. این فایل ساخته شده کاملا خالی است و معمولا زمانی کاربرد دارد که کاربر هنوز داده ای برای ذخیره کردن ندارد]`
    1. `[برای اهداف شمارشی ایجاد شده است؛ با اجرای آن میتوان تعداد خطوط،  تعداد کلمات و حروف یک فایل را بدست آورد. ]`
    1. `[ این دستور سیگنالی به پردازه مد نظر (که ورودی گرفته) میفرستد. این سیگنال میتواند سبب پایان یافتن اجرای پردازه شود ، اینکه اجرای آن را معوق کند،  وقفه ای ایجاد کند و … . این دستور باید توسط مالک (والد یا والد والدان و …) پردازه اجرا شود. فرمت آن kill [options] [process_ids] است.]`

- [ ] Write commands for these operations:
    - [ 
![image](https://github.com/Sharif-OS-Lab/session-1-2/assets/45389014/9c2ba4ea-e2b9-4b1b-ac7c-191811f22a2c)
] `[wc -l mybook.txt]`
    - [ 
![image](https://github.com/Sharif-OS-Lab/session-1-2/assets/45389014/9f4c7a2b-2fc1-4fe0-a7ad-b38502c09de2)
] `[ls -dq A* | wc -l]`
    - [ 
![image](https://github.com/Sharif-OS-Lab/session-1-2/assets/45389014/b805c8d7-c47d-477d-b5b2-a5f819d156f8)
] `[du -h mybook.txt`

### Section 1.4.1

- [ ] Get kernel with apt-get
    - [
![image](https://github.com/Sharif-OS-Lab/session-1-2/assets/45389014/215c6a7a-3dff-4a96-bd03-c93d5f5ba1dd)
![image](https://github.com/Sharif-OS-Lab/session-1-2/assets/45389014/59893d02-c090-41c6-bff3-0afe5a81e020)
 ] `[FILL HERE with screen capture of subtask 1]`
- [ ] Get tools for compiling kernel
    - [ 
![image](https://github.com/Sharif-OS-Lab/session-1-2/assets/45389014/6b603aa7-e86b-4941-8bdb-3f3d2f60b521)
] `[FILL HERE with screen capture of subtask 2]`
- [ ] Do subtask 3
    - [ 
![image](https://github.com/Sharif-OS-Lab/session-1-2/assets/45389014/54500289-774c-4474-b55d-6d335aa99afb)
![image](https://github.com/Sharif-OS-Lab/session-1-2/assets/45389014/3a07448e-617a-4887-a9a5-593ea25dad7b)
] `[FILL HERE with screen capture of subtask 3]`
   

### Section 1.4.2

- [ ] Compile kernel
    - [![image](https://github.com/Sharif-OS-Lab/session-1-2/assets/45389014/02c45d90-8c8b-4b87-8c24-308fc86304d2) 
![image](https://github.com/Sharif-OS-Lab/session-1-2/assets/45389014/51bdec30-e437-4b34-b5e9-e9555388b0c3)
] `[FILL HERE with screen capture of compiling kernel]`

- [ ] Install compiled kernel
    - [
![image](https://github.com/Sharif-OS-Lab/session-1-2/assets/45389014/4936906f-3278-4ded-bdb2-efdb115d5b5b)
![image](https://github.com/Sharif-OS-Lab/session-1-2/assets/45389014/2ef941a3-e79b-484d-9f97-46c2a452e795)
 ] `[FILL HERE with screen capture of installing compiled kernel]`

**Comment by shimynimi** [comment]
95
