### ISSUE TITLE
Session 1 Report

### ISSUE THREAD

**Issue by sarazm2000** [Sharif-OS-Lab/session-1-2#45]
Team Name: `98170849-98109729`

Student Name of member 1: `[Sara Zahedi]`
Student No. of member 1: `[98170849]`

Student Name of member 2: `[Paniz Halvah]`
Student No. of member 2: `[98109729]`

- [x] Read Session Contents.

### Section 1.3.1
- [x] Choose one of Virtual Machine Softwares, such as VirtualBox, VMware, ...
    1. [ ] `VirtualBox`
- [ ] Install Debian on Virtual Machine, add three screenshots from install process
    1. [ ]
![Screenshot (2868)](https://github.com/Sharif-OS-Lab/session-1-2/assets/63396470/f9e61c88-3eaa-4b30-bf51-f84327e94aa9)

    1. [ ] 
![Screenshot (2869)](https://github.com/Sharif-OS-Lab/session-1-2/assets/63396470/1601d6cb-dab4-4fa6-b4ed-f4ad6f4f852b)

    1. [ ] 
![Screenshot (2870)](https://github.com/Sharif-OS-Lab/session-1-2/assets/63396470/6c837f6d-181b-423a-872a-2307e86cc1fc)

    1. [ ] 
![Screenshot (2871)](https://github.com/Sharif-OS-Lab/session-1-2/assets/63396470/2873c89d-3d9f-46d3-8002-5ebd0ddc4c97)

![VirtualBox_debian_18_10_2023_02_44_04](https://github.com/Sharif-OS-Lab/session-1-2/assets/63396470/fdef7b5f-23ea-41d2-970e-6ee7216156e7)
![VirtualBox_debian_18_10_2023_02_46_52](https://github.com/Sharif-OS-Lab/session-1-2/assets/63396470/99fd9e0a-e36f-46aa-bca9-ecc1dd98121b)

![VirtualBox_deb1_18_10_2023_03_19_39](https://github.com/Sharif-OS-Lab/session-1-2/assets/63396470/9746107d-337e-4990-abbb-55f37e288859)

### Section 1.3.2

- [ ] Do 13 subtasks from 1 to 13 and add screenshots of each:
    1. [ ] `pwd, cd, mkdir`
![VirtualBox_deb1_18_10_2023_03_52_41](https://github.com/Sharif-OS-Lab/session-1-2/assets/63396470/b0020e0b-a242-4e20-aaab-9a2c102cef27)

    1. [ ] `[FILL HERE with screen capture of subtask 4]`
    
![VirtualBox_deb1_18_10_2023_03_54_47](https://github.com/Sharif-OS-Lab/session-1-2/assets/63396470/82878d00-0704-4b06-b84f-6f13f1f47ac9)
![VirtualBox_deb1_18_10_2023_03_55_40](https://github.com/Sharif-OS-Lab/session-1-2/assets/63396470/f7486fde-f95a-458b-90c8-f8196ff25b02)

    1. [ ] `[FILL HERE with screen capture of subtask 5]`
![VirtualBox_deb1_18_10_2023_03_58_40](https://github.com/Sharif-OS-Lab/session-1-2/assets/63396470/bdcd9765-a279-4e75-ba0b-049a70a2b246)

    1. [ ] `` 
![VirtualBox_deb1_18_10_2023_04_00_08](https://github.com/Sharif-OS-Lab/session-1-2/assets/63396470/105a4cc4-29f4-4f03-8150-fad3411bccb7)

    1. [ ] `[FILL HERE with screen capture of subtask 7]`
![VirtualBox_deb1_18_10_2023_04_01_22](https://github.com/Sharif-OS-Lab/session-1-2/assets/63396470/7ece62da-7e54-4a7a-97c7-c1e3a50eaa6b)

    1. [ ] `همانطور که در تصویر قابل مشاهده است این دو دستور با هم تفاوت دارند.  دستور اولی فایل را overwrite میکند ولی دستور دوم متن را به فایل append میکند.`
![VirtualBox_deb1_18_10_2023_04_03_33](https://github.com/Sharif-OS-Lab/session-1-2/assets/63396470/89ebf5e1-094a-48d7-9479-6e18f81eeef3)

    1. [ ] `[FILL HERE with screen capture of subtask 9]`
![VirtualBox_deb1_18_10_2023_04_09_23](https://github.com/Sharif-OS-Lab/session-1-2/assets/63396470/97fc3de7-ff49-49e2-bd90-830926ef0f2a)

    1. [ ] `[FILL HERE with screen capture of subtask 10]`
![VirtualBox_deb1_18_10_2023_04_10_40](https://github.com/Sharif-OS-Lab/session-1-2/assets/63396470/8531d302-0bfb-46c1-8f45-3dc1cf775c28)

    1. [ ] `[FILL HERE with screen capture of subtask 11]`
![VirtualBox_deb1_18_10_2023_04_12_39](https://github.com/Sharif-OS-Lab/session-1-2/assets/63396470/e8e39122-11b6-407b-9796-15e4a205ee5f)

    1. [ ] `[FILL HERE with screen capture of subtask 12]`
![VirtualBox_deb1_18_10_2023_04_14_48](https://github.com/Sharif-OS-Lab/session-1-2/assets/63396470/bc935ea1-6461-4b58-ac5d-cb1c93f4012c)

    1. [ ] `[FILL HERE with screen capture of subtask 13]`
![VirtualBox_deb1_18_10_2023_04_15_45](https://github.com/Sharif-OS-Lab/session-1-2/assets/63396470/4cb88e52-4791-40a1-b6da-02f325f32335)

1. [ ] `[FILL HERE with screen capture of subtask 14]` 
![VirtualBox_deb1_18_10_2023_04_17_26](https://github.com/Sharif-OS-Lab/session-1-2/assets/63396470/c62b7f2e-e969-4ae6-b81d-f3fe8f8ddabb)

- For subtask 7 write difference between `>` and `>>`
    - [ ] >: این دستور محتوای داده شده را روی فایل مینویسد و فایل را میسازد یا اگر از قبل وجود داشته باشد overwrite میکند اگر از قبل وجود داشته باشد اما >> اگر فایل وجود نداشته باشد آن را میسازد، در غیر اینصورت از به فایل append میکند.

## Section 1.4 

- [ ] Write (in English or Persian) about each command:
    1. `[cut: ]` cut: برای برش قسمتی از متن و کپی کزدن متن یا تصاویر از صفحه نمایشی که در حال حاضر روی آن کار می کنید استفاده می شود.
    1. `[FILL HERE with description about find]` برای جست و جو در فایل ها و دایرکتوری ها در سیستم فایل استفاده میشود. همچنین میتواند براساس نوع فایل، جست و جو، اندازه و تاریخ فایل حست و جو کند.
    1. `[FILL HERE with description about head]`  برای نمایش نخستین خطوط یک فایل است که به صورت پیشفرض این دستور 5 خط اول را نشان میدهد.
    1. `[FILL HERE with description about tail]` مانند دستور بالایی است اما این خطوط پایانی را نمایش میدهد و پیشفرض 5 خط است.
    1. `[FILL HERE with description about touch]` برای ایجاد یک فایل خالی استفاده میشود و اگر از قبل وجود داشته باشد تاریخش به زمان حال تغییر میکند.
    1. `[FILL HERE with description about wc]` برای شمارش تعداد خطوط در یک فایل متنی از این دستور استفاده میکنیم.
    1. `[FILL HERE with description about kill]`  برای متوقف کردن یک یا چند پردازه در لینوکس استفاده میشود

- [ ] Write commands for these operations:
    - [ ] `[FILL HERE with commands for finding line count in mybook.txt]`
![VirtualBox_deb1_18_10_2023_04_35_36](https://github.com/Sharif-OS-Lab/session-1-2/assets/63396470/a81c69fe-11c8-4ac4-854e-1ca2f8ca5c46)
![VirtualBox_deb1_18_10_2023_04_37_01](https://github.com/Sharif-OS-Lab/session-1-2/assets/63396470/61eada64-8838-4fdf-98bb-a39ecad8ee73)

    - [ ] `[FILL HERE with commands for finding files starting with A]`
![VirtualBox_deb1_18_10_2023_04_38_59](https://github.com/Sharif-OS-Lab/session-1-2/assets/63396470/8c183b5e-3d6a-42a2-a2ab-6452c2f85406)

    - [ ] `[FILL HERE with commands for finding size of mybook.txt]`
![VirtualBox_deb1_18_10_2023_04_40_35](https://github.com/Sharif-OS-Lab/session-1-2/assets/63396470/62237555-9d2b-4d96-b74f-1ee04bf99d44)

### Section 1.4.1

- [ ] Get kernel with apt-get
    - [ ] `[FILL HERE with screen capture of subtask 1]`
    

- [ ] Get tools for compiling kernel
    - [ ] `[FILL HERE with screen capture of subtask 2]`
- [ ] Do subtask 3
    - [ ] `[FILL HERE with screen capture of subtask 3]`
   

### Section 1.4.2

- [ ] Compile kernel
    - [ ] `[FILL HERE with screen capture of compiling kernel]`

- [ ] Install compiled kernel
    - [ ] `[FILL HERE with screen capture of installing compiled kernel]`

    1. [ ] `[FILL HERE with screen capture of subtask 5]`
    1. [ ] `[FILL HERE with screen capture of subtask 6]`
    1. [ ] `[FILL HERE with screen capture of subtask 7]`
    1. [ ] `[FILL HERE with screen capture of subtask 8]`
    1. [ ] `[FILL HERE with screen capture of subtask 9]`
    1. [ ] `[FILL HERE with screen capture of subtask 10]`
    1. [ ] `[FILL HERE with screen capture of subtask 11]`
    1. [ ] `[FILL HERE with screen capture of subtask 12]`
    1. [ ] `[FILL HERE with screen capture of subtask 13]`

- For subtask 7 write difference between `>` and `>>`
    - [ ]

## Section 1.4 

- [ ] Write (in English or Persian) about each command:
    1. `[FILL HERE with description about cut]`
    1. `[FILL HERE with description about find]`
    1. `[FILL HERE with description about head]`
    1. `[FILL HERE with description about tail]`
    1. `[FILL HERE with description about touch]`
    1. `[FILL HERE with description about wc]`
    1. `[FILL HERE with description about kill]`

- [ ] Write commands for these operations:
    - [ ] `[FILL HERE with commands for finding line count in mybook.txt]` wc -l mybook.txt
    - [ ] `[FILL HERE with commands for finding files starting with A]` find . type f -name 'A*' | wc -l
    - [ ] `[FILL HERE with commands for finding size of mybook.txt]` du -h mybook.txt

### Section 1.4.1

- [ ] Get kernel with apt-get
    - [ ] `[FILL HERE with screen capture of subtask 1]`
![Screenshot (2875)](https://github.com/Sharif-OS-Lab/session-1-2/assets/63396470/00dd85c1-7df2-4b4a-b01f-f0746b2cb375)

- [ ] Get tools for compiling kernel
    - [ ] `[FILL HERE with screen capture of subtask 2]`
![Screenshot (2875)](https://github.com/Sharif-OS-Lab/session-1-2/assets/63396470/111a1324-c7c2-4cd5-a75a-2199ae513b36)

- [ ] Do subtask 3
    - [ ] `[FILL HERE with screen capture of subtask 3]`
![Screenshot (2875)](https://github.com/Sharif-OS-Lab/session-1-2/assets/63396470/ca5ab025-d509-4f9c-a06a-e48b8f8bbc20)
![Screenshot (2875)](https://github.com/Sharif-OS-Lab/session-1-2/assets/63396470/427151a9-c751-4a07-b88b-c4dbf0ca65a6)

   

### Section 1.4.2

- [ ] Compile kernel
    - [ ] `[FILL HERE with screen capture of compiling kernel]` Install pakages: apt install git fakeroot build-essential ncurses-dev xz-utils libssl-dev bc flex libelf-dev bison
    - [ ] 
![VirtualBox_deb1_18_10_2023_06_25_09](https://github.com/Sharif-OS-Lab/session-1-2/assets/63396470/c8cfaadc-ed85-473d-9859-13746b37fe68)

    - [ ] Copy the kernel compile config file: cp /boot/config-5.10.0-21-amd64 .config
    - [ ] compile the kernel: make -j4 wher 4 is the number of cores

- [ ] Install compiled kernel
    - [ ] `[FILL HERE with screen capture of installing compiled kernel]`
    - [ ] make modules_install
    - [ ] make install
    - [ ] 
![Screenshot (2877)](https://github.com/Sharif-OS-Lab/session-1-2/assets/63396470/8fd3b530-6f48-460b-afbe-8e4edf720012)

**Comment by shimynimi** [comment]
100
